/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-09-04 14:14:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import in.mindcraft.pojos.ProductInCart;
import java.util.List;

public final class customerdashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("in.mindcraft.pojos.ProductInCart");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>Bootstrap demo</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9\" crossorigin=\"anonymous\">\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("  \r\n");
      out.write("   <div class=\"alert alert-");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" role=\"alert\" id=\"errorAlert\">\r\n");
      out.write("	    ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${successMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("    \r\n");
      out.write("            <script>\r\n");
      out.write("                setTimeout(function() {\r\n");
      out.write("                    var errorAlert = document.getElementById('errorAlert');\r\n");
      out.write("                    if (errorAlert) {\r\n");
      out.write("                        errorAlert.style.display = 'none';\r\n");
      out.write("                    }\r\n");
      out.write("                }, 4000); // Hide after 4 seconds\r\n");
      out.write("            </script>\r\n");
      out.write("  \r\n");
      out.write("    \r\n");
      out.write("    <div class=\"container ms-2 my-3\">\r\n");
      out.write("    	<h2>Hello, ");
      out.print( request.getAttribute("user") );
      out.write("</h2>\r\n");
      out.write("    	<h3>Your wallet balance: ");
      out.print( request.getAttribute("walletBalance") );
      out.write("</h3>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"cotainer mt-3 ms-3 me-3 my-3\">\r\n");
      out.write("    	<h3 style=\"text-align: center\">Product Details</h3>\r\n");
      out.write("    <table class=\"table table-bordered\">\r\n");
      out.write("        <thead>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <th>Product no</th>\r\n");
      out.write("            <th>Product Name</th>\r\n");
      out.write("            <th>Product price</th>\r\n");
      out.write("            <th>Product quantity</th>\r\n");
      out.write("            <th>Product discount</th>\r\n");
      out.write("        </tr>\r\n");
      out.write("        </thead>\r\n");
      out.write("        <tbody>\r\n");
      out.write("		");
 List<in.mindcraft.pojos.Product> products = (List<in.mindcraft.pojos.Product>) request.getAttribute("products");
        for(int i=0;i<products.size();i++){
        	in.mindcraft.pojos.Product product = products.get(i);
        
        
      out.write("\r\n");
      out.write("        \r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>");
      out.print(product.getProduct_no());
      out.write("</td>\r\n");
      out.write("	            <td>");
      out.print(product.getProduct_name());
      out.write("</td>\r\n");
      out.write("	            <td>");
      out.print(product.getProduct_price());
      out.write("</td>\r\n");
      out.write("	            <td>");
      out.print(product.getQuantity());
      out.write("</td>\r\n");
      out.write("	            <td>");
      out.print(product.getDiscount());
      out.write("</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            ");
 
            }
            
      out.write("\r\n");
      out.write("        </tbody>\r\n");
      out.write("    </table>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"mb-3\">\r\n");
      out.write("       <button type=\"button\" class=\"btn btn-primary\" data-bs-toggle=\"modal\" data-bs-target=\"#exampleModal1\">Add to cart</button>\r\n");
      out.write("       <button  type=\"button\" class=\"btn btn-primary\" data-bs-toggle=\"modal\" data-bs-target=\"#exampleModal2\">Display cart</button>\r\n");
      out.write("       <button  type=\"button\" class=\"btn btn-primary\" data-bs-toggle=\"modal\" data-bs-target=\"#exampleModal3\">Remove from cart</button>\r\n");
      out.write("       \r\n");
      out.write("	\r\n");
      out.write("		\r\n");
      out.write("		<!-- Modal 1-->\r\n");
      out.write("		<div class=\"modal fade\" id=\"exampleModal1\" tabindex=\"-1\" aria-labelledby=\"exampleModal1\" aria-hidden=\"true\">\r\n");
      out.write("		  <div class=\"modal-dialog\">\r\n");
      out.write("		    <div class=\"modal-content\">\r\n");
      out.write("		      <div class=\"modal-header\">\r\n");
      out.write("		        <h1 class=\"modal-title fs-5\" id=\"exampleModal1\">Add to cart</h1>\r\n");
      out.write("		        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("		      </div>\r\n");
      out.write("		      <div class=\"modal-body\">\r\n");
      out.write("		        \r\n");
      out.write("		        \r\n");
      out.write("		                <div class=\"container\">\r\n");
      out.write("					        	<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/addtocart\" method=\"post\">\r\n");
      out.write("								  \r\n");
      out.write("								  <div class=\"mb-3\">\r\n");
      out.write("								    <label for=\"cusid\" class=\"form-label\">Customer id</label>\r\n");
      out.write("								    <input type=\"text\" name=\"cusid\" value=");
      out.print( request.getAttribute("cusid") );
      out.write(" class=\"form-control\" id=\"cusid\">\r\n");
      out.write("								  </div>\r\n");
      out.write("								  \r\n");
      out.write("								  <div class=\"mb-3\">\r\n");
      out.write("								    <label for=\"pname\" class=\"form-label\">Product name</label>\r\n");
      out.write("								    <input type=\"text\" name=\"pname\" class=\"form-control\" id=\"pname\">\r\n");
      out.write("								  </div>\r\n");
      out.write("								 \r\n");
      out.write("								  <div class=\"mb-3\">\r\n");
      out.write("								    <label for=\"pquant\" class=\"form-label\">Product quantity</label>\r\n");
      out.write("								    <input type=\"number\" name=\"pquant\" class=\"form-control\" id=\"pquant\">\r\n");
      out.write("								  </div>\r\n");
      out.write("								  \r\n");
      out.write("								  <button type=\"submit\" class=\"btn btn-primary\">Submit</button>\r\n");
      out.write("								</form>\r\n");
      out.write("					        </div>\r\n");
      out.write("		        \r\n");
      out.write("		        \r\n");
      out.write("		      </div>\r\n");
      out.write("		      <div class=\"modal-footer\">\r\n");
      out.write("		        <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Close</button>\r\n");
      out.write("		        <button type=\"button\" class=\"btn btn-primary\">Save changes</button>\r\n");
      out.write("		      </div>\r\n");
      out.write("		    </div>\r\n");
      out.write("		  </div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		<!-- Modal 2-->\r\n");
      out.write("		<div class=\"modal fade\" id=\"exampleModal2\" tabindex=\"-1\" aria-labelledby=\"exampleModal2\" aria-hidden=\"true\">\r\n");
      out.write("		  <div class=\"modal-dialog\">\r\n");
      out.write("		    <div class=\"modal-content\">\r\n");
      out.write("		      <div class=\"modal-header\">\r\n");
      out.write("		        <h1 class=\"modal-title fs-5\" id=\"exampleModal2\">Your Cart</h1>\r\n");
      out.write("		        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("		      </div>\r\n");
      out.write("		      <div class=\"modal-body\">\r\n");
      out.write("		      \r\n");
      out.write("		      \r\n");
      out.write("		        <!-- Add the table for the cart with the \"Total Amount\" column -->\r\n");
      out.write("			<table class=\"table table-bordered\">\r\n");
      out.write("			    <thead>\r\n");
      out.write("			    <tr>\r\n");
      out.write("			        <th>Product Name</th>\r\n");
      out.write("			        <th>Product Price</th>\r\n");
      out.write("			        <th>Product Quantity</th>\r\n");
      out.write("			        <th>Total Amount</th> <!-- New column -->\r\n");
      out.write("			    </tr>\r\n");
      out.write("			    </thead>\r\n");
      out.write("			    <tbody>\r\n");
      out.write("			    ");

			        List<ProductInCart> items = (List<in.mindcraft.pojos.ProductInCart>) request.getAttribute("items");
			        double cartTotal = 0; // Initialize cart total
			        for (int i = 0; i < items.size(); i++) {
			            in.mindcraft.pojos.ProductInCart item = items.get(i);
			            double totalAmount = item.getProduct_price() * item.getProduct_quantity();
			            cartTotal += totalAmount; // Update cart total
			
			    
      out.write("\r\n");
      out.write("			    <tr>\r\n");
      out.write("			        <td>");
      out.print( item.getProduct_name() );
      out.write("</td>\r\n");
      out.write("			        <td>");
      out.print( item.getProduct_price() );
      out.write("</td>\r\n");
      out.write("			        <td>");
      out.print( item.getProduct_quantity() );
      out.write("</td>\r\n");
      out.write("			        <td>");
      out.print( totalAmount );
      out.write("</td> <!-- Display total amount for each product -->\r\n");
      out.write("			    </tr>\r\n");
      out.write("			    ");

			        }
			    
      out.write("\r\n");
      out.write("			    </tbody>\r\n");
      out.write("			</table>\r\n");
      out.write("                \r\n");
      out.write("             <!-- Display the total cart amount at the end of the table -->\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("			    <h4>Total Cart Amount: ");
      out.print( cartTotal );
      out.write("</h4>\r\n");
      out.write("			</div>\r\n");
      out.write("    \r\n");
      out.write("		      </div>\r\n");
      out.write("		      <div class=\"modal-footer\">\r\n");
      out.write("		        <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Close</button>\r\n");
      out.write("		        <button type=\"button\" onclick=\"proceedToCheckout()\" class=\"btn btn-primary\">Proceed to checkout</button>\r\n");
      out.write("		      </div>\r\n");
      out.write("		      \r\n");
      out.write("		      <script>\r\n");
      out.write("			    function proceedToCheckout() {\r\n");
      out.write("			        // Send an AJAX request to the server to check if the balance is sufficient and deduct the amount\r\n");
      out.write("			        var customer_id = ");
      out.print( request.getAttribute("cusid") );
      out.write("\r\n");
      out.write("			        var cartTotal = ");
      out.print( cartTotal );
      out.write("; // Get the cart total from JSP\r\n");
      out.write("			        \r\n");
      out.write("			        // You can use JavaScript's fetch() or an AJAX library like jQuery for the AJAX request\r\n");
      out.write("			        fetch(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/finalcheckout?cartTotal=\" + cartTotal + \"&customer_id=\" + customer_id, {\r\n");
      out.write("					    method: 'POST'\r\n");
      out.write("					})\r\n");
      out.write("			        .then(response => response.json())\r\n");
      out.write("			        .then(data => {\r\n");
      out.write("			            if (data.success) {\r\n");
      out.write("			                // Redirect to a success page or do something else\r\n");
      out.write("			                window.location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/finalcheckout\";\r\n");
      out.write("			            } else {\r\n");
      out.write("			                // Handle insufficient balance error or other errors\r\n");
      out.write("			                alert(\"Error: \" + data.message);\r\n");
      out.write("			            }\r\n");
      out.write("			        })\r\n");
      out.write("			        .catch(error => {\r\n");
      out.write("			            console.error('Error:', error);\r\n");
      out.write("			        });\r\n");
      out.write("			    }\r\n");
      out.write("	</script>\r\n");
      out.write("		      \r\n");
      out.write("		    </div>\r\n");
      out.write("		  </div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		<!-- Modal 3-->\r\n");
      out.write("		<div class=\"modal fade\" id=\"exampleModal3\" tabindex=\"-1\" aria-labelledby=\"exampleModal3\" aria-hidden=\"true\">\r\n");
      out.write("		  <div class=\"modal-dialog\">\r\n");
      out.write("		    <div class=\"modal-content\">\r\n");
      out.write("		      <div class=\"modal-header\">\r\n");
      out.write("		        <h1 class=\"modal-title fs-5\" id=\"exampleModal3\">Remove items</h1>\r\n");
      out.write("		        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("		      </div>\r\n");
      out.write("		      <div class=\"modal-body\">\r\n");
      out.write("		        ...\r\n");
      out.write("		      </div>\r\n");
      out.write("		      <div class=\"modal-footer\">\r\n");
      out.write("		        <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Close</button>\r\n");
      out.write("		        <button type=\"button\" class=\"btn btn-primary\">Save changes</button>\r\n");
      out.write("		      </div>\r\n");
      out.write("		    </div>\r\n");
      out.write("		  </div>\r\n");
      out.write("		</div>\r\n");
      out.write("		 \r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("          \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js\" integrity=\"sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js\" integrity=\"sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
